version: "3.9"

name: MongoCluster
services:
    mongo1:
        image: mongo:latest
        container_name: mongo1
        volumes:
            - d:/volumes/mongo/node1:/data/db
        command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
        ports:
            - 27017:27017
        networks:
            - mongoCluster
    mongo2:
        image: mongo:latest
        container_name: mongo2
        volumes:
            - d:/volumes/mongo/node2:/data/db
        command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
        ports:
            - 27018:27017
        networks:
            - mongoCluster
    mongo3:
        image: mongo:latest
        container_name: mongo3
        volumes:
            - d:/volumes/mongo/node3:/data/db
        command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
        ports:
            - 27019:27017
        networks:
            - mongoCluster

networks:
    mongoCluster:
        external: true
        name: mongoCluster