version: "3.9"
services:
  dev-local-jira:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "18009:8080"
    environment:
      - TZ=Asia/Tehran
    mem_limit: 4096M
    volumes:
      - c:/volumes/jira/jira-data:/var/atlassian/jira
    networks:
      - confluent-apps

  dev-local-jira-sql-db:
    image: sql-server-2022:latest
    container_name: dev-local-jira-db-host
    restart: always
    environment:
      SA_PASSWORD: "123456aA@"
      ACCEPT_EULA: "Y"
    ports:
      - "1430:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "123456aA@","-C", "-Q", "SELECT 1"]
      interval: 5s
      retries: 2
      start_period: 15s
    networks:
      - confluent-apps

  dev-local-jira-sql-db-init:
    image: sql-server-2022:latest
    depends_on:
      dev-local-jira-sql-db:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/sh", "-c", "echo 'SQL Server is ready! Running script...' && /opt/mssql-tools18/bin/sqlcmd -S dev-local-jira-db-host -U SA -P '123456aA@' -C -d master -i /scripts/init.sql"]
    restart: "no"
    networks:
      - confluent-apps
volumes:
  mssql_data:

networks:
  confluent-apps:
    driver: bridge