version: "3.9"

services:
  dev-local-jira:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "18009:8080"
    environment:
      - TZ=Asia/Tehran
    mem_limit: 4096M
    volumes:
      - c:/volumes/jira/jira-data:/var/atlassian/jira
    networks:
      - jira-network

  dev-local-jira-sql-db:
    # image: sql-server-2022:latest
    build:
      context: .
      dockerfile: dockerfile.sqlserver  # Use the custom Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123456aA@
    shm_size: 1g
    ports:
      - "1430:1433"
    volumes:
      - c:/volumes/jira/sql/data:/var/opt/mssql/data
      - c:/volumes/jira/sql/log:/var/opt/mssql/log
      - c:/volumes/jira/sql/secrets:/var/opt/mssql/secrets
      - ./sql-server-database-script.sql:/sql-server-database-script.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: [ "/bin/bash", "-c", "/docker-entrypoint-initdb.d/init-db.sh" ]
    restart: always
    networks:
      - jira-network

networks:
  jira-network:
    driver: bridge