version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "123456aA@"
      ACCEPT_EULA: "Y"
    ports:
      - "1430:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "123456aA@","-C", "-Q", "SELECT 1"]
      interval: 5s
      retries: 2
      start_period: 15s

  mssql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/sh", "-c", "echo 'SQL Server is ready! Running script...' && /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U SA -P '123456aA@' -C -d master -i /scripts/init.sql"]
    restart: "no"

volumes:
  mssql_data: