{
 "title": "MongoDB信息",
 "description": "MongoDB数据库监控，中文版",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "groups",
    "label": "groups",
    "query": "label_values(mongodb_connections, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(mongodb_connections{job=~\"$groups\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "运行时间",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "数据库版本",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "mongodb_version_info{instance=~\"$instance\"}",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  {
   "title": "磁盘操作的页面错误总数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_extra_info_page_faults_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "集群健康",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "mongodb_mongod_replset_member_health{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{name}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "集群状态",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_state{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "节点数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cache的开销",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_overhead_percent{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mongodb状态",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "mongodb_up{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "超时的cursors 数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_cursor_timed_out_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "虚拟内存",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$instance\",type=~\"virtual\"}"
    }
   ]
  },
  {
   "title": "数据库个数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(mongodb_mongod_db_data_size_bytes{ instance=~\"$instance\",db!=\"local\",db!=\"admin\"})"
    }
   ]
  },
  {
   "title": "物理内存",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$instance\",type=~\"resident\"}"
    }
   ]
  },
  {
   "title": "数据库操作",
   "type": "graph",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "连接数" }
   ],
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$instance\",state=~\"current|available\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "客户端读写",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_client{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "读写锁",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mongodb_mongod_global_lock_current_queue{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "文件操作",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "主从同步延时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "缓存区数据大小",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Oplog Size(日志大小)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_oplog_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}