version: '3.9'

services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus-standalone
    ports:
      - 9090:9090
    # command:
    #   - '--config.file=/etc/prometheus/prometheus.yml' ## this config is for prom/prometheus image
    volumes:
      # - ./config/prometheus.yml:/etc/prometheus/prometheus.yaml ## this config is for prom/prometheus image
      - ./config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      # - prometheus-data:/prometheus ## this config is for prom/prometheus image
    restart: unless-stopped
    networks:
      - monitoring

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - monitoring
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin 
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana-data:/var/lib/grafana

networks:
  monitoring:

volumes:
  grafana-data: